export const TOGGLE_APP_MENU = 'TOGGLE_APP_MENU';
export const TOGGLE_THEME = 'TOGGLE_THEME';
export const SET_CURRENT_PROJECT = "SET_CURRENT_PROJECT";
export const ADD_PROJECT = "ADD_PROJECT";
export const SET_MENU_NAME = "SET_MENU_NAME";
export const SET_NEEDS_REPEAT = "SET_NEEDS_REPEAT";
export const SET_DTMF_OPTIONS = "SET_DTMF_OPTIONS";
export const SET_DEFAULT_ROUTE_TO = "SET_DEFAULT_ROUTE_TO";